Repository microsoft/Power-Fx, pull requests merged in 2023-04, with the labels that each got.

#1287 Refactor Features to hide all Power Apps-specific flags
  src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs
  src/libraries/Microsoft.PowerFx.Core/Functions/BuiltinFunction.cs
  src/libraries/Microsoft.PowerFx.Core/Functions/Delegation/DelegationStrategies/DelegationValidationStrategy.cs
  src/libraries/Microsoft.PowerFx.Core/Functions/Delegation/DelegationStrategies/InOpDelegationStrategy.cs
  src/libraries/Microsoft.PowerFx.Core/Functions/Delegation/DelegationStrategies/OpDelegationStrategy.cs
  src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs
  src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs
  src/libraries/Microsoft.PowerFx.Core/Parser/TexlParser.cs
  src/libraries/Microsoft.PowerFx.Core/Public/Config/FeatureExtensions.cs
  src/libraries/Microsoft.PowerFx.Core/Public/Config/Features.cs
  src/libraries/Microsoft.PowerFx.Core/Public/Config/PowerFxConfig.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/AddColumns.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/ColorFadeT.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/DateTime.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/DropColumns.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/FirstLastN.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/IsEmpty.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/LeftRight.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/MathFunction.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Mid.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Replace.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Round.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Sort.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/SortByColumns.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/StringOneArgFunction.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Substitute.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Trunc.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Intellisense/SuggestionHandlers/FirstNameNodeSuggestionHandler.cs
  src/libraries/Microsoft.PowerFx.Core/Utils/Hashing.cs
  src/tests/Microsoft.PowerFx.Connectors.Tests/IntellisenseTests.cs
  src/tests/Microsoft.PowerFx.Connectors.Tests/OpenApiParserTests.cs
  src/tests/Microsoft.PowerFx.Connectors.Tests/PowerPlatformConnectorTests.cs
  src/tests/Microsoft.PowerFx.Core.Tests/DisplayNameOptionSetTests.cs
  src/tests/Microsoft.PowerFx.Core.Tests/DisplayNameTests.cs
  src/tests/Microsoft.PowerFx.Core.Tests/IntellisenseTests/SuggestTest.cs
  src/tests/Microsoft.PowerFx.Core.Tests/TestRunnerTests/InternalSetup.cs
  src/tests/Microsoft.PowerFx.Core.Tests/TestRunnerTests/InternalSetupTests.cs
  src/tests/Microsoft.PowerFx.Core.Tests/TexlTests.cs
  src/tests/Microsoft.PowerFx.Interpreter.Tests/CustomFunctions.cs
  src/tests/Microsoft.PowerFx.Interpreter.Tests/DisplayNameTests.cs
  src/tests/Microsoft.PowerFx.Interpreter.Tests/FlagTests.cs
  src/tests/Microsoft.PowerFx.Interpreter.Tests/GetTokensUtilsTest.cs
  src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/LanguageServerTests.cs
  src/tests/Microsoft.PowerFx.Interpreter.Tests/PadUntypedObjectTests.cs
  src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineAsyncTests.cs
  src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
  src/tests/Microsoft.PowerFx.Interpreter.Tests/SandboxTests.cs
  src/tests/Microsoft.PowerFx.Performance.Tests/BasicPerformance.cs
  src/tests/Microsoft.PowerFx.Performance.Tests/PvaPerformance.cs
  src/tools/Repl/Program.cs
Labels: Breaking Internals, Breaking API

#1392 976 - Remove most public Obsolete methods.
  src/libraries/Microsoft.PowerFx.Core/Public/Config/PowerFxConfig.cs
  src/libraries/Microsoft.PowerFx.Core/Public/Engine.cs
  src/libraries/Microsoft.PowerFx.Core/Public/IExpression.cs
  src/libraries/Microsoft.PowerFx.Core/Public/IPowerFxEngine.cs
  src/libraries/Microsoft.PowerFx.Core/Public/Values/DateTimeValue.cs
  src/libraries/Microsoft.PowerFx.Core/Public/Values/DateValue.cs
  src/libraries/Microsoft.PowerFx.Interpreter/ParsedExpression.cs
  src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngine.cs
  src/libraries/Microsoft.PowerFx.Interpreter/RecalcEngineScope.cs
  src/libraries/Microsoft.PowerFx.LanguageServerProtocol/LanguageServer/IPowerFxScopeQuickFix.cs
  src/tests/Microsoft.PowerFx.Core.Tests/PublicSurfaceTests.cs
  src/tests/Microsoft.PowerFx.Interpreter.Tests/LanguageServiceProtocol/PublicSurfaceTests.cs
  src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
Labels: Breaking API

#1378 Support decimal return values for integer returning functions
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Count.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/CountA.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/CountIf.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/CountRows.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/DateTime.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Hex2Dec.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/Len.cs
  src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/RandBetween.cs
  src/libraries/Microsoft.PowerFx.Interpreter/Functions/Library.cs
  src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryDate.cs
  src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryMath.cs
  src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryTable.cs
  src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/DecimalIntReturn.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/DecimalNonMathFuncs.txt
  src/tests/Microsoft.PowerFx.Core.Tests/TexlTests.cs
  src/tests/Microsoft.PowerFx.Interpreter.Tests/DateTimeUTCTests.cs
  src/tests/Microsoft.PowerFx.Interpreter.Tests/RecalcEngineTests.cs
Labels: Breaking Language

#1408 Reversing the default for ReservedKeywords
  src/libraries/Microsoft.PowerFx.Core/Lexer/TexlLexer.cs
  src/libraries/Microsoft.PowerFx.Core/Parser/ParserExtensions.cs
  src/libraries/Microsoft.PowerFx.Core/Parser/ParserOptions.cs
  src/libraries/Microsoft.PowerFx.Core/Parser/TexlParser.cs
  src/libraries/Microsoft.PowerFx.Core/Public/Config/Features.cs
  src/libraries/Microsoft.PowerFx.Core/Public/Engine.cs
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ReservedKeywordNegative.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/ReservedKeywordPositive.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ParseTests.cs
  src/tests/Microsoft.PowerFx.Core.Tests/TexlTests.cs
  src/tests/Microsoft.PowerFx.Interpreter.Tests/PowerFxEvaluationTests.cs
  src/tools/Repl/Program.cs
Labels: Breaking Language

#1422 Update Time function to stop 'wrapping around' values beyond 24h
  src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryDate.cs
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Date.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/DateAdd_TimeZone_Beirut.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OpMatrix_Eq_Decimal_V1Compat.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OpMatrix_Eq_Decimal_V1CompatDisabled.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OpMatrix_Eq_Float_V1Compat.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OpMatrix_Eq_Float_V1CompatDisabled.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OpMatrix_Geq_Decimal.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OpMatrix_Geq_Float.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OpMatrix_Gt_Decimal.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OpMatrix_Gt_Float.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OpMatrix_Leq_Decimal.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OpMatrix_Leq_Float.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OpMatrix_Lt_Decimal.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OpMatrix_Lt_Float.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OpMatrix_Neq_Decimal_V1Compat.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OpMatrix_Neq_Decimal_V1CompatDisabled.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OpMatrix_Neq_Float_V1Compat.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/OpMatrix_Neq_Float_V1CompatDisabled.txt
  src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Time.txt
Labels: Breaking Internals, Breaking Language

#1447 Renamed HasErrors to HasErrorsOrWarnings.
  src/libraries/Microsoft.PowerFx.Core/App/Controls/IExternalRule.cs
  src/libraries/Microsoft.PowerFx.Core/Binding/Binder.cs
Labels: Breaking Internals
